name: Documentation
description: Report a documentation issue or suggest documentation improvements
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve DevPockit's documentation! Please fill out the form below.

  - type: dropdown
    id: type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - "Missing Documentation"
        - "Incorrect Information"
        - "Unclear/Confusing"
        - "Outdated Content"
        - "Typo/Grammar"
        - "Formatting Issue"
        - "Other"
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is this documentation issue? (e.g., README.md, CONTRIBUTING.md, specific tool docs)
      placeholder: "e.g., README.md, CONTRIBUTING.md, docs/ARCHITECTURE.md"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the documentation issue or improvement
      placeholder: A clear and concise description of the documentation issue
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Content (if applicable)
      description: What does the documentation currently say?
      placeholder: Paste the current documentation content here
    validations:
      required: false

  - type: textarea
    id: suggested
    attributes:
      label: Suggested Change (if applicable)
      description: What should the documentation say instead?
      placeholder: Describe or paste the suggested documentation content
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the documentation issue
      placeholder: Any additional information that might be helpful
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this documentation issue has not already been reported
          required: true
        - label: I have provided all the information requested above
          required: true

